name: Main Mock
on:
  push:
    branches:
    - "main"

env:
  VERSION: v5

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Reusable Workflow Scripts
        uses: actions/checkout@v3
        with:
          repository: hboavent/api-fortify-mock
          ref: main
          path: .github/actions
          # token: ${{ secrets.PAT_SVCALMIACP }}

      - run: ls -lah

      - uses: ./action-test@v1