name: Main Mock
on:
  push:
    branches:
    - "main"

env:
  VERSION: v5

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:

      # - name: Checkout Reusable Workflow Scripts
      #   uses: actions/checkout@v3
      #   with:
      #     repository: hboavent/action-test
      #     ref: main
      #     # path: .github/actions

      # - run: |
          # ls -lah .github/actions
          # tree .

      - uses: hboavent/action-test/.github/actions/action-test@main
