name: Main Mock
on:
  push:
    branches:
    - "main"

jobs:
  step-1:
    uses: ./.github/workflows/step.yml
    name: Teste
    with:
      message: ${{ github.event.head_commit.message }}
      skip-bump: true
