# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: 'Test scenario tags'
        required: true
        type: string
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  step-1:
    name: Maven Test
    runs-on: ubuntu-latest
    steps:
      - name: Maven Test
        run: mvn test

  step-2:
    name: Maven Test Again
    needs: step-1
    runs-on: ubuntu-latest
    steps:
      - name: Maven Test again
        run: mvn test
