# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  # Setting an environment variable with the value of a configuration variable
  version: '1.0.0'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  step-1:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - id: get-version
        run: echo "version=1.0.0" >> "$GITHUB_OUTPUT"

  step-2:
    runs-on: ubuntu-latest
    needs: step-1
    steps:
      - name: Dummy
        run: echo dummy

  step-3:
    runs-on: ubuntu-latest
    needs: step-2
    steps:
      - name: Dummy
        run: echo dummy
  step-3-1:
    runs-on: ubuntu-latest
    needs: step-2
    steps:
      - name: Dummy
        run: echo dummy

  step-4:
    runs-on: ubuntu-latest
    needs: [step-1, step-3]
    steps:
      - name: Change version
        run: echo ${{ needs.step-3.outputs.version }}
