name: Main Mock
on:
  push:
    branches:
    - "main"

env:
  VERSION: v5

jobs:
  step-1:
    uses: ./.github/workflows/step-1.yml
    name: Test
  step-2: 
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: broa
        run: |
          echo 'Henrique'
          echo '${{ vars.jacutinga }}
          mkdir '${{ vars.jacutinga }}
  
