# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_call:

jobs:
  step-1:
    name: Teste
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event.head_commit.message }}
