name: CI

on:
  push:
    branches:
      - main

jobs:
  step-1:
    uses: ./.github/workflows/step.yml
    name: Teste
    with:
      message: ${{ github.event.head_commit.message }}

  step-2:
    runs-on: ubuntu-latest
    needs: step-1
    steps:
      - run: echo '${{ needs.step-1.outputs.version }}'


