# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: 'Test scenario tags'
        required: true
        type: string
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true

jobs:
  print-tag:
    name: GMUDI REQUI
    runs-on: ubuntu-latest
    environment: gmud
    steps:
      - name: Print the input tag to STDOUT
        run: echo  The tags are ${{ inputs.tags }} 
  print-tag-2:
    runs-on: ubuntu-latest
    needs: print-tag
    environment: ${{ inputs.environment }}
    steps:
      - name: Print the input tag to STDOUT
        run: echo  The tags are ${{ inputs.tags }} 
  something:
    runs-on: ubuntu-latest
    needs: print-tag-2
    steps:
      - name: Print the input tag to STDOUT
        run: echo  The tags are ${{ inputs.tags }} 
  print-tag-3:
    runs-on: ubuntu-latest
    needs: print-tag-2
    environment: ${{ inputs.environment }}
    steps:
      - name: Print the input tag to STDOUT
        run: echo  The tags are ${{ inputs.tags }} 
