name: Main Mock
on:
  push:
    branches:
    - "main"

env:
  VERSION: v5

jobs:
  step-1:
    uses: ./.github/workflows/step-1.yml
    if: 1 == 2
    name: Test
  step-2:
    uses: ./.github/workflows/step-1.yml
    if: 1==2
    name: Test 2
  step-3:
    runs-on: ubuntu-latest
    needs: [step-1, step-2]    
    if: always() &&
      needs.step-1.result == 'success' &&
      (needs.step-2.result == 'success' || needs.step-2.result == 'skipped')
    environment: dev
    steps:
      - name: broa
        run: |
          echo 'Henrique'
          echo '${{ vars.jacutinga }}'
          mkdir '${{ vars.jacutinga }}'
