name: Bump version

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string
      skip-bump:
        type: boolean
        default: false
    outputs:
      version:
        value: ${{ jobs.bump-version.outputs.version }}

jobs:
  bump-version:
    runs-on: ubuntu-latest
    continue-on-error: true
    outputs:
      version: ${{ env.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get current version
        id: current-version
        run: echo "version=1.0.0" >> "$GITHUB_OUTPUT"

      - name: Get commit prefix
        uses: actions-ecosystem/action-regex-match@v2
        id: semantic-tag
        with:
          text: ${{ inputs.message }}
          regex: '^(major|minor|patch)'

      - uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        with:
          current_version: ${{ steps.current-version.outputs.version }}
          level: ${{ steps.semantic-tag.outputs.match == '' && 'patch' || steps.semantic-tag.outputs.group1 }}

      - name: Update version
        if: ${{ inputs.skip-bump == false }}
        run: |
          echo "version=${{ steps.bump-semver.outputs.new_version }}" >> "$GITHUB_ENV"
          echo '${{ env.version }}'

      - name: Keep version
        if: ${{ inputs.skip-bump == true }}
        run: |
          echo "version=${{ steps.current-version.outputs.version }}" >> "$GITHUB_ENV"
          echo '${{ env.version }}'