name: Step 2

on:
  workflow_call:

jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Teste
        id: teste
        run: echo "teste 2"